"""modify playertable FK

Revision ID: 998a2d4d4a96
Revises: b80ff3414dcc
Create Date: 2025-09-28 17:49:13.599790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998a2d4d4a96'
down_revision = 'b80ff3414dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
